### ISSUE TITLE
Case sensitive - bug

### ISSUE THREAD

**Issue by steom** [mjpclab/go-http-file-server#10]
-a|--alias separator|url-path|separator|fs-path
The url-path is case sensitive, 
While it should case insensitive like everything else

**Comment by marjune163** [comment]
Hi, url-path is considered to be case sensitive. That's because on unix like system, file and directory names are always case sensitive.

For example there are two directories on file system in same parent directory, one is `Abc` and another is `abc`. Both of them will be displayed in list if server is a unix like system. When you set alias for `Abc`, the other one `abc` is still available and accessiable.

**Comment by steom** [comment]
hello,
yes, on unix.
please consider at least for the windows version to get rid ot this, and render the url-path case insensitive.

**Comment by marjune163** [comment]
Please use version 1.12.0 with option `--bind`, which creates url-case-insensitive alias.

**Comment by steom** [comment]
just tried,
works fine! thanks!
